services:
  - type: web
    name: inventory75
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 2 -k gthread -b 0.0.0.0:\ --preload
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory75-db
          property: connectionString
databases:
  - name: inventory75-db
    plan: free
